spring.application.name=Du_An_Tot_Nghiep_F6

spring.web.resources.static-locations=classpath:/static/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

#SQL SERVER CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=your_database_name
spring.datasource.username=your_username
spring.datasource.password=yout_password
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.error.whitelabel.enabled=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh

#spring.mail.from = your_email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email_username
spring.mail.password=your_email_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.servlet.session.timeout=2d


#VNPAY CONFIG
payment.vnPay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnPay.tmnCode= 58X4B4HP
payment.vnPay.secretKey= VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
payment.vnPay.returnUrl= http://localhost:8080/home/check-out/credit_card
payment.vnPay.version= 2.1.0
payment.vnPay.command= pay
payment.vnPay.orderType= other

#MOMO CONFIG
DEV_MOMO_ENDPOINT=https://test-payment.momo.vn/v2/gateway/api
DEV_ACCESS_KEY=mTCKt9W3eU1m39TW
DEV_PARTNER_CODE=MOMOLRJZ20181206
DEV_SECRET_KEY=SetA5RDnLHvt51AULf51DyauxUo3kDU6
##Configuration for production environment
PROD_MOMO_ENDPOINT=https://payment.momo.vn/v2/gateway/api
PROD_ACCESS_KEY=key
PROD_PARTNER_CODE=key
PROD_SECRET_KEY=key

## AIOv2
CREATE_URL=/create
QUERY_URL=/query
REFUND_URL=/refund
CONFIRM_URL=/confirm
TOKEN_PAY_URL=/tokenization/pay
TOKEN_BIND_URL=/tokenization/bind
TOKEN_INQUIRY_URL=/tokenization/cbQuery
TOKEN_DELETE_URL=/tokenization/delete